name: Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
        default: 'v1.0.0'
      release_type:
        description: 'Release type (stable, beta, rc)'
        required: true
        default: 'stable'

jobs:
  call-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: gouef/release-action@main
        with:
          branch: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: pip install tweepy

      - name: Send tweet
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          python - <<EOF
          import tweepy
          import os

          client = tweepy.OAuth1UserHandler(
              os.getenv("TWITTER_API_KEY"),
              os.getenv("TWITTER_API_SECRET"),
              os.getenv("TWITTER_ACCESS_TOKEN"),
              os.getenv("TWITTER_ACCESS_TOKEN_SECRET")
          )
          api = tweepy.API(client)

          tweet_text = f"ðŸš€ New version of {os.getenv('GITHUB_REF_NAME')} just released! ðŸŽ‰\n\n{os.getenv('GITHUB_SERVER_URL')}/{os.getenv('GITHUB_REPOSITORY')}/releases/latest"

          response = api.update_status(text=tweet_text)
          print(f"Tweet odeslÃ¡n: {response}")
          EOF
